/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from 'ethers'
import { Provider } from '@ethersproject/providers'
import type { IDepository, IDepositoryInterface } from '../IDepository'

const _abi = [
    {
        inputs: [
            {
                components: [
                    {
                        internalType: 'contract IERC20',
                        name: 'token',
                        type: 'address',
                    },
                    {
                        internalType: 'uint256',
                        name: 'amount',
                        type: 'uint256',
                    },
                    {
                        internalType: 'uint256',
                        name: 'nonce',
                        type: 'uint256',
                    },
                ],
                internalType: 'struct DepositoryTypes.Deposit',
                name: 'd',
                type: 'tuple',
            },
            {
                components: [
                    {
                        internalType: 'contract IDepositUnlocker',
                        name: 'unlocker',
                        type: 'address',
                    },
                    {
                        internalType: 'bytes',
                        name: 'condition',
                        type: 'bytes',
                    },
                ],
                internalType: 'struct DepositoryTypes.Unlocker',
                name: 'u',
                type: 'tuple',
            },
        ],
        name: 'depositID',
        outputs: [
            {
                internalType: 'DepositID',
                name: '',
                type: 'bytes32',
            },
        ],
        stateMutability: 'pure',
        type: 'function',
    },
    {
        inputs: [
            {
                components: [
                    {
                        internalType: 'contract IERC20',
                        name: 'token',
                        type: 'address',
                    },
                    {
                        internalType: 'uint256',
                        name: 'amount',
                        type: 'uint256',
                    },
                    {
                        internalType: 'uint256',
                        name: 'nonce',
                        type: 'uint256',
                    },
                ],
                internalType: 'struct DepositoryTypes.Deposit',
                name: 'deposit',
                type: 'tuple',
            },
            {
                components: [
                    {
                        internalType: 'contract IDepositUnlocker',
                        name: 'unlocker',
                        type: 'address',
                    },
                    {
                        internalType: 'bytes',
                        name: 'condition',
                        type: 'bytes',
                    },
                ],
                internalType: 'struct DepositoryTypes.Unlocker',
                name: 'unlocker',
                type: 'tuple',
            },
        ],
        name: 'lock',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
    },
    {
        inputs: [
            {
                components: [
                    {
                        internalType: 'contract IERC20',
                        name: 'token',
                        type: 'address',
                    },
                    {
                        internalType: 'uint256',
                        name: 'amount',
                        type: 'uint256',
                    },
                    {
                        internalType: 'uint256',
                        name: 'nonce',
                        type: 'uint256',
                    },
                ],
                internalType: 'struct DepositoryTypes.Deposit',
                name: 'deposit',
                type: 'tuple',
            },
            {
                components: [
                    {
                        internalType: 'contract IDepositUnlocker',
                        name: 'unlocker',
                        type: 'address',
                    },
                    {
                        internalType: 'bytes',
                        name: 'condition',
                        type: 'bytes',
                    },
                ],
                internalType: 'struct DepositoryTypes.Unlocker',
                name: 'unlocker',
                type: 'tuple',
            },
            {
                internalType: 'bytes',
                name: 'solution',
                type: 'bytes',
            },
        ],
        name: 'unlock',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
    },
]

export class IDepository__factory {
    static readonly abi = _abi
    static createInterface(): IDepositoryInterface {
        return new utils.Interface(_abi) as IDepositoryInterface
    }
    static connect(address: string, signerOrProvider: Signer | Provider): IDepository {
        return new Contract(address, _abi, signerOrProvider) as IDepository
    }
}
