/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
    BaseContract,
    BigNumber,
    BigNumberish,
    BytesLike,
    CallOverrides,
    ContractTransaction,
    Overrides,
    PopulatedTransaction,
    Signer,
    utils,
} from 'ethers'
import { FunctionFragment, Result } from '@ethersproject/abi'
import { Listener, Provider } from '@ethersproject/providers'
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from './common'

export declare namespace BtcRefundUnlocker {
    export type ConditionStruct = { refundAddress: BytesLike }

    export type ConditionStructOutput = [string] & { refundAddress: string }

    export type SolutionStruct = {
        stableBridgingFee: BigNumberish
        clientID: BytesLike
    }

    export type SolutionStructOutput = [BigNumber, string] & {
        stableBridgingFee: BigNumber
        clientID: string
    }
}

export declare namespace DepositoryTypes {
    export type DepositStruct = {
        token: string
        amount: BigNumberish
        nonce: BigNumberish
    }

    export type DepositStructOutput = [string, BigNumber, BigNumber] & {
        token: string
        amount: BigNumber
        nonce: BigNumber
    }
}

export interface BtcRefundUnlockerInterface extends utils.Interface {
    contractName: 'BtcRefundUnlocker'
    functions: {
        'decodeCondition(bytes)': FunctionFragment
        'encodeCondition((bytes))': FunctionFragment
        'encodeSolution((uint256,bytes32))': FunctionFragment
        'synthesis()': FunctionFragment
        'unlock(address,(address,uint256,uint256),bytes,bytes)': FunctionFragment
    }

    encodeFunctionData(functionFragment: 'decodeCondition', values: [BytesLike]): string
    encodeFunctionData(functionFragment: 'encodeCondition', values: [BtcRefundUnlocker.ConditionStruct]): string
    encodeFunctionData(functionFragment: 'encodeSolution', values: [BtcRefundUnlocker.SolutionStruct]): string
    encodeFunctionData(functionFragment: 'synthesis', values?: undefined): string
    encodeFunctionData(
        functionFragment: 'unlock',
        values: [string, DepositoryTypes.DepositStruct, BytesLike, BytesLike]
    ): string

    decodeFunctionResult(functionFragment: 'decodeCondition', data: BytesLike): Result
    decodeFunctionResult(functionFragment: 'encodeCondition', data: BytesLike): Result
    decodeFunctionResult(functionFragment: 'encodeSolution', data: BytesLike): Result
    decodeFunctionResult(functionFragment: 'synthesis', data: BytesLike): Result
    decodeFunctionResult(functionFragment: 'unlock', data: BytesLike): Result

    events: {}
}

export interface BtcRefundUnlocker extends BaseContract {
    contractName: 'BtcRefundUnlocker'
    connect(signerOrProvider: Signer | Provider | string): this
    attach(addressOrName: string): this
    deployed(): Promise<this>

    interface: BtcRefundUnlockerInterface

    queryFilter<TEvent extends TypedEvent>(
        event: TypedEventFilter<TEvent>,
        fromBlockOrBlockhash?: string | number | undefined,
        toBlock?: string | number | undefined
    ): Promise<Array<TEvent>>

    listeners<TEvent extends TypedEvent>(eventFilter?: TypedEventFilter<TEvent>): Array<TypedListener<TEvent>>
    listeners(eventName?: string): Array<Listener>
    removeAllListeners<TEvent extends TypedEvent>(eventFilter: TypedEventFilter<TEvent>): this
    removeAllListeners(eventName?: string): this
    off: OnEvent<this>
    on: OnEvent<this>
    once: OnEvent<this>
    removeListener: OnEvent<this>

    functions: {
        decodeCondition(
            condition: BytesLike,
            overrides?: CallOverrides
        ): Promise<[BtcRefundUnlocker.ConditionStructOutput]>

        encodeCondition(c: BtcRefundUnlocker.ConditionStruct, overrides?: CallOverrides): Promise<[string]>

        encodeSolution(s: BtcRefundUnlocker.SolutionStruct, overrides?: CallOverrides): Promise<[string]>

        synthesis(overrides?: CallOverrides): Promise<[string]>

        unlock(
            metarouter: string,
            deposit: DepositoryTypes.DepositStruct,
            condition: BytesLike,
            solution: BytesLike,
            overrides?: Overrides & { from?: string | Promise<string> }
        ): Promise<ContractTransaction>
    }

    decodeCondition(condition: BytesLike, overrides?: CallOverrides): Promise<BtcRefundUnlocker.ConditionStructOutput>

    encodeCondition(c: BtcRefundUnlocker.ConditionStruct, overrides?: CallOverrides): Promise<string>

    encodeSolution(s: BtcRefundUnlocker.SolutionStruct, overrides?: CallOverrides): Promise<string>

    synthesis(overrides?: CallOverrides): Promise<string>

    unlock(
        metarouter: string,
        deposit: DepositoryTypes.DepositStruct,
        condition: BytesLike,
        solution: BytesLike,
        overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>

    callStatic: {
        decodeCondition(
            condition: BytesLike,
            overrides?: CallOverrides
        ): Promise<BtcRefundUnlocker.ConditionStructOutput>

        encodeCondition(c: BtcRefundUnlocker.ConditionStruct, overrides?: CallOverrides): Promise<string>

        encodeSolution(s: BtcRefundUnlocker.SolutionStruct, overrides?: CallOverrides): Promise<string>

        synthesis(overrides?: CallOverrides): Promise<string>

        unlock(
            metarouter: string,
            deposit: DepositoryTypes.DepositStruct,
            condition: BytesLike,
            solution: BytesLike,
            overrides?: CallOverrides
        ): Promise<void>
    }

    filters: {}

    estimateGas: {
        decodeCondition(condition: BytesLike, overrides?: CallOverrides): Promise<BigNumber>

        encodeCondition(c: BtcRefundUnlocker.ConditionStruct, overrides?: CallOverrides): Promise<BigNumber>

        encodeSolution(s: BtcRefundUnlocker.SolutionStruct, overrides?: CallOverrides): Promise<BigNumber>

        synthesis(overrides?: CallOverrides): Promise<BigNumber>

        unlock(
            metarouter: string,
            deposit: DepositoryTypes.DepositStruct,
            condition: BytesLike,
            solution: BytesLike,
            overrides?: Overrides & { from?: string | Promise<string> }
        ): Promise<BigNumber>
    }

    populateTransaction: {
        decodeCondition(condition: BytesLike, overrides?: CallOverrides): Promise<PopulatedTransaction>

        encodeCondition(c: BtcRefundUnlocker.ConditionStruct, overrides?: CallOverrides): Promise<PopulatedTransaction>

        encodeSolution(s: BtcRefundUnlocker.SolutionStruct, overrides?: CallOverrides): Promise<PopulatedTransaction>

        synthesis(overrides?: CallOverrides): Promise<PopulatedTransaction>

        unlock(
            metarouter: string,
            deposit: DepositoryTypes.DepositStruct,
            condition: BytesLike,
            solution: BytesLike,
            overrides?: Overrides & { from?: string | Promise<string> }
        ): Promise<PopulatedTransaction>
    }
}
