import { ChainId } from '../../constants'

export const COINGECKO_PLATFORMS: { [chainId in ChainId]?: string } = {
    [ChainId.BASE_MAINNET]: 'base',
    [ChainId.ETH_MAINNET]: 'ethereum',
    [ChainId.BSC_MAINNET]: 'binance-smart-chain',
    [ChainId.AVAX_MAINNET]: 'avalanche',
    [ChainId.MATIC_MAINNET]: 'polygon-pos',
    [ChainId.TELOS_MAINNET]: 'telos',
    [ChainId.BOBA_MAINNET]: 'boba',
    [ChainId.BOBA_BNB]: 'boba',
    [ChainId.KAVA_MAINNET]: 'kava',
    [ChainId.ZKSYNC_MAINNET]: 'zksync',
    [ChainId.ARBITRUM_MAINNET]: 'arbitrum-one',
    [ChainId.OPTIMISM_MAINNET]: 'optimistic-ethereum',
    [ChainId.ARBITRUM_NOVA]: 'arbitrum-nova',
    [ChainId.POLYGON_ZK]: 'polygon-zkevm',
    [ChainId.LINEA_MAINNET]: 'linea',
    [ChainId.MANTLE_MAINNET]: 'mantle',
    [ChainId.SCROLL_MAINNET]: 'scroll',
    [ChainId.MANTA_MAINNET]: 'manta-pacific',
    [ChainId.METIS_MAINNET]: 'metis-andromeda',
    [ChainId.MODE_MAINNET]: 'mode',
    [ChainId.RSK_MAINNET]: 'rootstock',
    [ChainId.BLAST_MAINNET]: 'blast',
    [ChainId.MERLIN_MAINNET]: 'merlin-chain',
    [ChainId.ZKLINK_MAINNET]: 'zklink-nova',
    [ChainId.TON_MAINNET]: 'the-open-network',
    [ChainId.TON_TESTNET]: 'the-open-network',
    [ChainId.BTC_MAINNET]: 'bitcoin',
    [ChainId.TRON_MAINNET]: 'tron',
    [ChainId.TAIKO_MAINNET]: 'taiko',
    [ChainId.ZETACHAIN_MAINNET]: 'zetachain',
    [ChainId.CRONOS_MAINNET]: 'cronos',
    [ChainId.FRAXTAL_MAINNET]: 'fraxtal',
    [ChainId.GRAVITY_MAINNET]: 'gravity-alpha',
    [ChainId.BSQUARED_MAINNET]: 'bsquared-network',
    [ChainId.CRONOS_ZK_MAINNET]: 'cronos-zkevm',
}

export const COINGECKO_GAS_TOKEN_IDS: { [chainId in ChainId]?: string } = {
    [ChainId.BASE_MAINNET]: 'ethereum',
    [ChainId.ETH_MAINNET]: 'ethereum',
    [ChainId.BSC_MAINNET]: 'binancecoin',
    [ChainId.AVAX_MAINNET]: 'avalanche-2',
    [ChainId.MATIC_MAINNET]: 'matic-network',
    [ChainId.TELOS_MAINNET]: 'telos',
    [ChainId.BOBA_MAINNET]: 'ethereum',
    [ChainId.BOBA_BNB]: 'boba-network',
    [ChainId.KAVA_MAINNET]: 'kava',
    [ChainId.ZKSYNC_MAINNET]: 'ethereum',
    [ChainId.ARBITRUM_MAINNET]: 'ethereum',
    [ChainId.OPTIMISM_MAINNET]: 'ethereum',
    [ChainId.ARBITRUM_NOVA]: 'ethereum',
    [ChainId.POLYGON_ZK]: 'ethereum',
    [ChainId.LINEA_MAINNET]: 'ethereum',
    [ChainId.MANTLE_MAINNET]: 'mantle',
    [ChainId.SCROLL_MAINNET]: 'ethereum',
    [ChainId.MANTA_MAINNET]: 'ethereum',
    [ChainId.METIS_MAINNET]: 'metis-token',
    [ChainId.MODE_MAINNET]: 'ethereum',
    [ChainId.RSK_MAINNET]: 'rootstock',
    [ChainId.BLAST_MAINNET]: 'ethereum',
    [ChainId.MERLIN_MAINNET]: 'bitcoin',
    [ChainId.ZKLINK_MAINNET]: 'ethereum',
    [ChainId.TON_MAINNET]: 'the-open-network',
    [ChainId.TON_TESTNET]: 'the-open-network',
    [ChainId.BTC_MAINNET]: 'bitcoin',
    [ChainId.TRON_MAINNET]: 'tron',
    [ChainId.TAIKO_MAINNET]: 'ethereum',
    [ChainId.SEI_EVM_MAINNET]: 'sei-network',
    [ChainId.ZETACHAIN_MAINNET]: 'zetachain',
    [ChainId.CRONOS_MAINNET]: 'crypto-com-chain',
    [ChainId.FRAXTAL_MAINNET]: 'frax-ether',
    [ChainId.GRAVITY_MAINNET]: 'g-token',
    [ChainId.BSQUARED_MAINNET]: 'bitcoin',
    [ChainId.CRONOS_ZK_MAINNET]: 'cronos-zkevm-cro',
}
