export const TRON_TRC20_ABI = [
    {
        inputs: [],
        stateMutability: 'nonpayable',
        type: 'constructor',
    },
    {
        inputs: [
            { indexed: true, name: 'owner', type: 'address' },
            { indexed: true, name: 'spender', type: 'address' },
            { name: 'value', type: 'uint256' },
        ],
        name: 'Approval',
        type: 'event',
    },
    {
        inputs: [
            { indexed: true, name: 'from', type: 'address' },
            { indexed: true, name: 'to', type: 'address' },
            { name: 'value', type: 'uint256' },
        ],
        name: 'Transfer',
        type: 'event',
    },
    {
        outputs: [{ type: 'uint256' }],
        constant: true,
        inputs: [
            { name: 'owner', type: 'address' },
            { name: 'spender', type: 'address' },
        ],
        name: 'allowance',
        stateMutability: 'view',
        type: 'function',
    },
    {
        outputs: [{ type: 'bool' }],
        inputs: [
            { name: 'spender', type: 'address' },
            { name: 'value', type: 'uint256' },
        ],
        name: 'approve',
        stateMutability: 'nonpayable',
        type: 'function',
    },
    {
        outputs: [{ type: 'uint256' }],
        constant: true,
        inputs: [{ name: 'account', type: 'address' }],
        name: 'balanceOf',
        stateMutability: 'view',
        type: 'function',
    },
    {
        outputs: [{ type: 'uint8' }],
        inputs: [],
        constant: true,
        name: 'decimals',
        stateMutability: 'view',
        type: 'function',
    },
    {
        outputs: [{ type: 'bool' }],
        inputs: [
            { name: 'spender', type: 'address' },
            { name: 'subtractedValue', type: 'uint256' },
        ],
        name: 'decreaseAllowance',
        stateMutability: 'nonpayable',
        type: 'function',
    },
    {
        outputs: [{ type: 'bool' }],
        inputs: [
            { name: 'spender', type: 'address' },
            { name: 'addedValue', type: 'uint256' },
        ],
        name: 'increaseAllowance',
        stateMutability: 'nonpayable',
        type: 'function',
    },
    {
        inputs: [],
        outputs: [{ type: 'string' }],
        constant: true,
        name: 'name',
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [],
        outputs: [{ type: 'string' }],
        constant: true,
        name: 'symbol',
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [],
        outputs: [{ type: 'uint256' }],
        constant: true,
        name: 'totalSupply',
        stateMutability: 'view',
        type: 'function',
    },
    {
        outputs: [{ type: 'bool' }],
        inputs: [
            { name: 'recipient', type: 'address' },
            { name: 'amount', type: 'uint256' },
        ],
        name: 'transfer',
        stateMutability: 'nonpayable',
        type: 'function',
    },
    {
        outputs: [{ type: 'bool' }],
        inputs: [
            { name: 'sender', type: 'address' },
            { name: 'recipient', type: 'address' },
            { name: 'amount', type: 'uint256' },
        ],
        name: 'transferFrom',
        stateMutability: 'nonpayable',
        type: 'function',
    },
] as const
